@startuml

hide circle
skinparam linetype ortho

entity "DimensiCustomer" as customer {
    * id_customer
    nama
    no_telp
    email
    alamat
    negara
}

entity "DimensiWaktuTransaksiCustomer" as waktu_customer {
    * id_waktu_transaksi
    tanggal_pemesanan
    tangal_pembayaran
    tanggal_terima
}

entity "FaktaTransaksiCustomer" as transaksi_customer {
    * id_fakta_transaksi_customer
    id_customer <<FK>>
    id_waktu_transaksi <<FK>>
    id_pegawai <<FK>>
    id_produk <<FK>>
    id_metode_transaksi <<FK>>
    jumlah_transaksi
}

entity "DimensiPegawai" as pegawai {
    * id_pegawai
    id_departemen <<FK>>
    nama
    no_telp
    email
    alamat
    negara
}

entity "DimensiDepartemenPegawai" as departemen_pegawai {
    * id_departemen_pegawai
    departemen
}

entity "DimensiProduk" as produk {
    * id_produk
    id_kategori_produk <<FK>>
    id_stok_produk <<FK>>
    nama_produk
    harga
    tgl_kadaluarsa
}

entity "DimensiKategoriProduk" as kategori_produk {
    * id_kategori_produk
    kategori_produk
}

entity "DimensiStok" as stok_produk {
    * id_stok_produk
    id_waktu_stok <<FK>>
    stok
}

entity "DimensiWaktuStok" as waktu_stok {
    * id_waktu_stok
    tanggal
}

entity "DimensiMetodePembayaran" as metode_pembayaran {
    * id_metode_pembayaran
    nama_pembayaran
}

entity "FaktaPenggajian" as penggajian {
    * id_fakta_penggajian
    id_pegawai <<FK>>
    id_waktu_kerja <<FK>>
    id_gaji_pegawai <<FK>>
    id_metode_pembayaran <<FK>>
    total_gaji_pegawai
}

entity "FaktaTransaksiPengadaan" as transaksi_pengadaan {
    * id_fakta_transaksi_pengadaan
    id_pegawai <<FK>>
    id_waktu_transaksi_barang <<FK>>
    id_produk <<FK>>
    id_metode_pembayaran <<FK>>
    id_supplier <<FK>>
    jumlah_transaksi_barang
}

entity "DimensiWaktuKerja" as waktu_kerja {
    * id_waktu_kerja
    jam_masuk
    jam_keluar
}

entity "DimensiGajiPegawai" as gaji_pegawai {
    * id_gaji_pegawai
    id_bonus_gaji <<FK>>
    gaji_pokok
    tunjangan
    keterangan
}

entity "DimensiBonusGaji" as bonus_gaji {
    * id_bonus_gaji
    id_waktu_bonus <<FK>>
    bonus
}

entity "DimensiWaktuBonus" as waktu_bonus {
    * id_waktu_bonus
    tanggal
}

entity "DimensiWaktuTransaksiPengandaan" as waktu_pengadaan {
    * id_waktu_transaksi_barang
    tanggal_pemesanan
    tanggal_pembayaran
    tanggal_terima
}

entity "DimensiSupplier" as supplier {
    * id_supplier
    nama_supplier
    no_telp
    email
    alamat
    toko
    negara
}

customer ||..|{ transaksi_customer
waktu_customer ||..|{ transaksi_customer
pegawai ||..|{ transaksi_customer
produk ||..|{ transaksi_customer
metode_pembayaran ||..|{ transaksi_customer

pegawai ||..|{ penggajian
waktu_kerja ||..|{ penggajian
gaji_pegawai ||..|{ penggajian
bonus_gaji ||..|{ gaji_pegawai
waktu_bonus ||..|{ bonus_gaji

pegawai ||..|{ transaksi_pengadaan
produk ||..|{ transaksi_pengadaan
metode_pembayaran ||..|{ transaksi_pengadaan
waktu_pengadaan ||..|{ transaksi_pengadaan
supplier ||..|{ transaksi_pengadaan

kategori_produk ||..|{ produk
stok_produk ||..|{ produk
departemen_pegawai ||..|{ pegawai
waktu_stok ||..|{ stok_produk

@enduml








